# Generated by Django 5.0.7 on 2024-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_chord_alter_profile_profile_picture_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
